openapi: 3.0.3
info:
  title: Internflare Backend API
  version: 1.0.0
paths:
  /api/v1/auth/signup:
    post:
      summary: Signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Signup'
      responses:
        '201':
          description: Created
  /api/v1/auth/login:
    post:
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: OK
  /api/v1/feedback:
    post:
      summary: Submit feedback (auth required)
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feedback'
      responses:
        '201':
          description: Created
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Signup:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        name:
          type: string
      required: [email, password]
    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required: [email, password]
    Feedback:
      type: object
      properties:
        message:
          type: string
        rating:
          type: integer